### ISSUE TITLE
Deprecated symbols in IDA Python

### ISSUE THREAD

**Issue by depot-moose** [tmr232/Sark#102]
Hi.

I've just upgraded to IDA 7.7, and I'm getting a couple of deprecation warnings when using Sark, because some of the names in IDA Python have changed:

In core.py, **idaapi.cvar.inf.minEA** has been changed to **min_ea**, and similarly for **idaapi.cvar.inf.maxEA**.

In code/instruction.py, **idaapi.get_inf_structure().procName** has been changed to **procname**.

Kind regards

**Comment by tmr232** [comment]
Thank you for the report!

I am currently without an up-to-date IDA license, so I cannot test those things.
Feel free to submit a PR fixing the issues.

**Comment by tmr232** [comment]
closes #102
