### ISSUE TITLE
ARM indexing modes

### ISSUE THREAD

**Issue by tmr232** [tmr232/Sark#31]
Currently, Sark does not provide information about ARM pre-index and post-index options.

This can be done using `insn_t.auxpref`:

Flag | Meaning
------|-------------
0 | Regular indexing
0x20 | Pre-Index
0x80 | Post-Index

The main issue is whether to add it as a property of the instruction (probably), the operand (less likely), or both.

**Comment by ronyrus** [comment]
I would go with the instruction only approach.

**Comment by tmr232** [comment]
I uploaded a first draft of the API. `Instruction` objects now have a `indexing_mode` property of type `IndexingMode`. So you can use:

```python
# Check for pre-indexing
sark.Line().insn.indexing_mode.is_pre

# Check for post-indexing
sark.Line().insn.indexing_mode.is_post

# Check for normal addressing
sark.Line().insn.indexing_mode.is_none

# Another check for normal addressing
bool(sark.Line().insn.indexing_mode)
```

@ronyrus , I'd appreciate it if you can check it out and see if it works as expected.

**Comment by ronyrus** [comment]
seems to be working well :+1:

**Comment by tmr232** [comment]
Any inputs on the API?

**Comment by ronyrus** [comment]
Looks fine to me. Is there something specific bothering you?
