### ISSUE TITLE
data: native size iteration

### ISSUE THREAD

**Issue by ronyrus** [tmr232/Sark#33]
When traversing the pointer table, for example, it would make sense to traverse it with a native pointer size for the platform. This would allow to write code that would work for both 32 and 64 bit ARM platforms without modification.

**Comment by tmr232** [comment]
I added the relevant functions. Please tell me if this works for you.

**Comment by ronyrus** [comment]
looks good.

In my specific case, I ended up implementing wrappers as well.
Mostly because I needed the 'find_val()' and 'find_not_val()' functionality for data iteration forward and backward.

It might be a good idea to add reverse iteration and xxx_until_not().
What do you think?
Should I open a new issue?
