### ISSUE TITLE
proposition: make_string()

### ISSUE THREAD

**Issue by ronyrus** [tmr232/Sark#34]
Lets consider adding the make_string() to the data.py
For example, something like this:
```
def make_string(start, len=0):
    return idc.MakeStr(start, idaapi.BADADDR if len is 0 else start + len)
```

**Comment by tmr232** [comment]
How is that different than https://www.hex-rays.com/products/ida/support/sdkdoc/bytes_8hpp.html#aa09b7d24fa3e8080b5cf0f20d5bf60bd?

And I'm terribly sorry for the late response.
