### ISSUE TITLE
getting the bytes of the line object

### ISSUE THREAD

**Issue by ronyrus** [tmr232/Sark#45]
I propose to add a property to a line object.
A property that will return the bytes of the object.
something like:
` return idaapi.get_many_bytes(self.ea, self.size) `

**Comment by tmr232** [comment]
This sounds like a good idea. I'll look into it when I have the time.

It will probably be an iterable named `line.bytes` or something similar.

**Comment by ronyrus** [comment]
what's wrong with "get_many_bytes()" ?

**Comment by tmr232** [comment]
Most getters in Sark are implemented as properties. So it makes more sense to make this one a property too.  `get_many_bytes` is a weird name for one.

**Comment by ronyrus** [comment]
I agree. 
I didn't mean to name it `get_many_bytes` though.
I meant using `idaapi.get_many_bytes()` and returning the result instead of an iterator/generator.
`line.bytes` is perfect imho.

**Comment by tmr232** [comment]
That makes sense. I'll try and get to it soon. Feel free to submit a PR.
