### ISSUE TITLE
issue with anterior and posterior comments

### ISSUE THREAD

**Issue by proind** [tmr232/Sark#53]
in case an anterior or posterior comment has an empty line anywhere, 
the text after the empty  line doesn't appear. 

seems like the empty line is treated as None and   
` return "\n".join(iter(lines.next, None))`
stops when it gets to it

**Comment by tmr232** [comment]
Verified. Thanks!

**Comment by proind** [comment]
I have a workaround for this and another issue with interior/posterior comments , but the branch includes the code for my previous pull request  #52 , so I'm not sure whether to submit it

**Comment by tmr232** [comment]
Yeah... Sorry for taking so long with accepting the PR.
