### ISSUE TITLE
can not debug plugin after being reloaded

### ISSUE THREAD

**Issue by yuanbaopapa** [tmr232/Sark#58]
class IdaTestPlugin(idaapi.plugin_t):
    flags = idaapi.PLUGIN_UNL

test code as above,setting flags to  idaapi.PLUGIN_UNL ,that makes the plugin unloaded after running,and the plugin will be reloaded on the next time.however i can only debug at the first time.the visual studio does not break the script after reloaded.

**Comment by tmr232** [comment]
Can you try using the debugger initialization code in your own plugin instead, and see if that works?

I am not sure what is causing the issue, and it might be a while before I have time to properly investigate it.

**Comment by yuanbaopapa** [comment]
it seems like a bug of visualstudio iteself, resolved by moving to pydevd+pycharm solution
