### ISSUE TITLE
CodeBlock equality is not implemented

### ISSUE THREAD

**Issue by oded-el** [tmr232/Sark#59]
Hi,

When you write:
`block_list = [sark.CodeBlock()]`
`sark.CodeBlock() in block_list`

you get False.
It would be very nice to have equality of CodeBlocks so it won't be necessary to write my own equality function.

**Comment by tmr232** [comment]
That seems a great idea. I'll try to get to it as soon as I can.
Feel free to submit a PR in the meantime.

**Comment by tmr232** [comment]
Can you take a look and see that the PR fixes the issue for you?

**Comment by oded-el** [comment]
Yea it fixes, thank you
