### ISSUE TITLE
Incorrect documentation for functions' module.

### ISSUE THREAD

**Issue by OfficialMan** [tmr232/Sark#6]
The following miscellaneous documentation page contains incorrect module names for the mentioned functions.
https://github.com/tmr232/Sark/blob/master/docs/api/Miscellaneous.rst

e.g. The get_ea function is written in the [sark.core module](https://github.com/tmr232/Sark/blob/72839a944556be8257232977b0d51e1160166409/sark/core.py#L31). However, it's not imported to the [init module](https://github.com/tmr232/Sark/blob/72839a944556be8257232977b0d51e1160166409/sark/__init__.py) of the sark package. Therefore, it cannot be accessed without using the absolute module name of the function (which should be sark.core.get_ea).

It can be solved by importing specific functions from the core module (in the init module) or modifying the Misc's documentation page.

**Comment by tmr232** [comment]
Looking at it, I can't really see any reason to export the `get_func` function either. I should probably remove both from the documentation and the `__init__.py` file.

**Comment by tmr232** [comment]
Since the main issue is the docs, I will just remove it from there.
