### ISSUE TITLE
Error showing NXGraph

### ISSUE THREAD

**Issue by oded-el** [tmr232/Sark#62]
`import sark`
`graph = sark.get_nx_graph(sark.Function().ea)`
`viewer = sark.ui.NXGraph(graph, title="My Graph", handler=sark.ui.AddressNodeHandler())`
`viewer.Show()`
creates the following error message:
![image](https://user-images.githubusercontent.com/5565756/26972060-cf61e882-4cc4-11e7-9d98-7c0cf30ee210.png)

**Comment by tmr232** [comment]
I've seen this error in the past, but had no luck yet solving it.
Can you give some information on what triggered it?
OS, IDA version, architecture of IDB, anything that might be useful.

**Comment by oded-el** [comment]
Windows 7, IDA 64bit 6.8.150423, x64 elf binary.
The Show() method trigged it

**Comment by tmr232** [comment]
Any chance you can share an elf or IDB that reproduces it?

**Comment by oded-el** [comment]
I can tell for sure that the problem is in the _OnNodeInfo function in NXGraph class.
The error occurs when calling self.SetNodeInfo(node_id_ node_info, flags)

**Comment by tmr232** [comment]
@oded-el Does this reproduce in IDA 7?

**Comment by tmr232** [comment]
Finally got around to it...
From my testing, it seems to be an issue with IDA itself. I contacted support and am waiting for their reply.

**Comment by tmr232** [comment]
Confirmed with Hex-Rays that this is a bug in IDA. I'll update as soon as I have anything more to say.

**Comment by tmr232** [comment]
Got the response from Hex Rays.
The bug was in the following line - https://github.com/idapython/src/blob/master/pywraps.cpp#L1513 - an `ea` not a `ulong`.
The attached file is a fix for IDA7.3. If you need a fix for another version, contact support.

[idapython.zip](https://github.com/tmr232/Sark/files/3495902/idapython.zip)
