### ISSUE TITLE
pip install fails

### ISSUE THREAD

**Issue by acepace** [tmr232/Sark#66]
```
 Could not find a version that satisfies the requirement idacute (from sark) (from versions: )
No matching distribution found for idacute (from sark)

```
Using Python 3.6.2

**Comment by argp** [comment]
Same error here.

**Comment by tmr232** [comment]
Sorry for the long response-time.
IDA is still using Python 2.7. Therefore, I did not package idacute for Python 3.

**Comment by argp** [comment]
idacute installed manually and then using pip for sark works fine.
