### ISSUE TITLE
IDA 7.0 cannot import Sark when running python script

### ISSUE THREAD

**Issue by NSExceptional** [tmr232/Sark#97]
<img width="50%" src="https://user-images.githubusercontent.com/8371943/119897095-8ca07600-bf05-11eb-9b47-be07fac10d63.png">

Meanwhile, `python` can `import sark` just fine, and Pylance finds the module when I tell it to look where my pip2 modules are installed (`/usr/local/lib/python2.7/site-packages`).

I am starting IDA like this:
```bash
ida -S/path/to/script.py my_binary
```

OS: **macOS**
IDA Pro version: **7.0**
Python version: **2.7.17**
Installed sark using: `pip2 install "sark<7.4"`

**Comment by NSExceptional** [comment]
#13 solved my issue. I needed to install everything inside IDA itself. I ran the `get-pip.py` script for Python 2.7 since that is what IDA Pro 7.0 ships with, then I restarted IDA (necessary) and ran the following commands to install sark:

```python
> import pip
> pip.main(args=['install', 'sark<7.1'])
```

**Comment by nav60** [comment]
Hi. Thanks 
It helped me to fix networkx on IDAPRO. Thanks

**Comment by nav60** [comment]
Hi. Thanks 
It helped me to fix networkx on IDAPRO. Thanks
