### ISSUE TITLE
"Expected an ea_t type" when calling `sark.Segment("__TEXT")`

### ISSUE THREAD

**Issue by NSExceptional** [tmr232/Sark#99]
Not sure what this means :P

<img width="100%" src="https://user-images.githubusercontent.com/8371943/119904457-0a697f00-bf10-11eb-989d-1e621d3f0f9f.png">

**Comment by tmr232** [comment]
If you want to get a segment by name, you need to use `sark.Segment(name="__TEXT")`.

**Comment by NSExceptional** [comment]
Ah! Thank you. I'm obviously not a python user. I tried `sark.Segment(None, theName)` and that gave another error so I gave up to wait for your reply. Thanks! And sorry
